language: node_js
node_js: 8

cache:
  yarn: true

notifications:
  email: false

deploy:
  provider: npm
  email:
    secure: PthZH3azXbaQVOyuqvKu82lEcnMENJtBJ52K5GquJdQuV4I4M5vZAb586qsXg+BPuwim9rPv5RNhRyzKGc4Lg2ZyLGVfa0duHOs6kabpmy8BGv2TgJj7sGz0NbfXjtyVdxSf+uRFOldEriuZh/FRxPQb3vGb3UOseLtgPKvNM+vee5K8jNHWVzBi7620E9fma1xYqVk3/ri8uH+nQw+YmoccTmDoHSLS0B37Mpj1NG3rEgX+AfW52IfvQtcIDtvUEigHc4sV/uNZ60Af8iuR8gbgMcTBM+xGjkPftwGP0gwEyKeWIm9UAcpS5FSMAXQQkzv2ISWzum1RisUbKkFp7n5Sm5yXiovXitVILUHHEHXi91qmb5R3EiMLtIgMYqyKipmM53V/cbtsRnZKl/ol5tYGwy9P6VxI0DcuiZWtvIkaU5U5w3y+PiZkyMXRTbRz7ZcsG8wUJVTX0vd63LY5DN9KGotTu/PxgpABoObfJk8TynNgzHtuuG6Ajb5KUeCTnc/gBQy8NtZVSybhR1oPO8w69lZv2KuQC5wko2gF4C28UeW/AsaXaxPQs3QiiNJdw5j+tffggAaPj5bvbBEUrAikjHHuXq7e97Ea9rZhNieXY5820qiVfhdcvTHfFQLRQidGF6w5gkS63OT1NAONiYulJUeaYna8EkAXguXXMxg=
  api_key:
    secure: ZUa+i95VCAjFu8ffMx8qVht6lqzwAbbtVRHtNcedsQbXOSMM6pJeJJqzjsIzFOjr3sM5NZh9ZYeBVDSpllYr1B+GArEsK4ZeByJUR1RhG1kAxn54huG/BxBiojC1PI/jab3oymL/9AiPzUEm9oyvSx4fW4aOVNdLmvU4p0kKDM/spvch14uzzJK4SolLAXMy4yS6U5XvEeMSUq48Pg6LfJjloOR9pHXOX/KAxybAMVd14HhYuaP3CVuDAhSybKlHdOdlpD/oFG21ZvWDZIaLMKflCegIOpAcwDR54xqqVqShypnH/qokUvEF4N2Km1ExeO5yXvHrCm3YvpWOxBL4PhDm9GYZJ3eP9oZXhSVHVr+bUZW2V3I0T/LLefLHw1uilIQ7qAIjDBaI/IDY+G1Cwhg7IfpZsGhCtocqkk4YPo6fp1lVO1bbZkGo42nRoB/oPs8039/TWqkugET/OL1tl/GBpM5OO5FmcW4ixz7Fd60Y3No0DTVI3unRhtSMYHHoJC8k3j8UXj8DQ7Lm7la7snTyVuCPdGt+mVM9Z+FNeM+28n7T8NBt9qBX6KNKYqmnyDj7NN2vr8t3+N6se79R0KsCOyw79rT0VoLMf2j6x3Grk/X5vrtl0etORftbwZhxdKKlYIMeOdGPSplUoHzxF+YXCifho7XBMi1ooUyJeLI=
  on:
    tags: true
    repo: thelounge/thelounge-theme-solarized
    branch: master
