name: Release

on:
  push:
    tags: v*

jobs:
  release:
    name: Release workflow

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Install
        run: yarn --frozen-lockfile --non-interactive

      - name: Publish latest
        if: "!contains(github.ref, '-')"
        run: npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Publish next
        if: contains(github.ref, '-')
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Remove next tag
        if: "!contains(github.ref, '-')"
        run: npm dist-tag rm thelounge-theme-solarized next || true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
